spring:
  application:
    name: spring-ai-01-chat
  datasource:
    url: jdbc:mysql://localhost:3306/Debt_Consolidation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



mybatis:
  mapper-locations: classpath:/com/example/springtext/mapper/*.xml

logging:
  level:
    org.springframework.security: DEBUG
