spring:
  application:
    name: spring-ai-01-chat
  datasource:
    url: jdbc:mysql://localhost:3306/Debt_Consolidation
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


mybatis:
  mapper-locations: classpath:/com/example/springtext/mapper/*.xml